/* main/http_upload.c */
#include "http_upload.h"

#include "app_config.h"
#include "ui.h"

#include <ctype.h>
#include <dirent.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>

#include "esp_http_server.h"
#include "esp_log.h"
#include "esp_lvgl_port.h"
#include "ff.h"

static const char *TAG = "HTTP_UPLOAD";

static httpd_handle_t s_upload_server = NULL;

/*
 * These symbols are generated by ESP-IDF from:
 *
 *     main/upload.html
 *
 * because we will add it to EMBED_FILES in CMakeLists.txt.
 */
extern const char upload_html_start[] asm("_binary_upload_html_start");
extern const char upload_html_end[] asm("_binary_upload_html_end");

/* --------------------------------------------------------------------------
 * Helpers
 * -------------------------------------------------------------------------- */
static bool is_valid_filename(const char *name)
{
    if (!name || name[0] == '\0')
    {
        return false;
    }

    size_t len = strlen(name);

    if (len < 5 || len > 64)
    {
        return false;
    }

    /* Must end in .pcm or .bmp */
    const char *ext = strrchr(name, '.');

    if (!ext)
    {
        return false;
    }

    if (strcasecmp(ext, ".pcm") != 0 && strcasecmp(ext, ".bmp") != 0)
    {
        return false;
    }

    /* Only allow safe alphanumeric characters, dot, dash, underscore */
    for (size_t i = 0; i < len; i++)
    {
        char c = name[i];

        if (!(isalnum((unsigned char)c) || c == '.' || c == '-' || c == '_'))
        {
            return false;
        }
    }

    return true;
}

static int status_append(char *buf, size_t size, int offset, const char *fmt, ...)
{
    if (buf == NULL || offset < 0 || (size_t)offset >= size)
    {
        return offset;
    }

    va_list args;
    va_start(args, fmt);

    int ret = vsnprintf(buf + offset, size - offset, fmt, args);

    va_end(args);

    if (ret < 0)
    {
        return (int)size;
    }

    return offset + ret;
}

/* --------------------------------------------------------------------------
 * HTTP handlers
 * -------------------------------------------------------------------------- */
static esp_err_t root_get_handler(httpd_req_t *req)
{
    httpd_resp_set_type(req, "text/html");

    size_t html_len = (size_t)(upload_html_end - upload_html_start);

    httpd_resp_send(req, upload_html_start, html_len);

    return ESP_OK;
}

static esp_err_t status_get_handler(httpd_req_t *req)
{
    const size_t buf_size = 2048;

    char *buf = malloc(buf_size);

    if (!buf)
    {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "OOM");
        return ESP_FAIL;
    }

    int offset = 0;

    offset = status_append(buf, buf_size, offset, "{\"free_mb\":");

    /* Calculate free space on SD card */
    FATFS *fs;
    DWORD fre_clust;

    if (f_getfree(SD_MOUNT_POINT, &fre_clust, &fs) == FR_OK)
    {
        /* fre_clust * csize = free sectors. Usually 512 bytes per sector. */
        uint32_t free_mb = (fre_clust * fs->csize) / 2048;

        offset = status_append(buf, buf_size, offset, "%lu", (unsigned long)free_mb);
    }
    else
    {
        offset = status_append(buf, buf_size, offset, "-1");
    }

    offset = status_append(buf, buf_size, offset, ",\"files\":[");

    /* List existing .pcm files */
    DIR *dir = opendir(SD_MOUNT_POINT);

    if (dir)
    {
        struct dirent *entry;
        bool first = true;

        while ((entry = readdir(dir)) != NULL)
        {
            if (entry->d_type == DT_REG)
            {
                const char *name = entry->d_name;
                int len = strlen(name);

                if (len > 4 && strcasecmp(name + len - 4, ".pcm") == 0)
                {
                    offset = status_append(
                        buf,
                        buf_size,
                        offset,
                        "%s\"%s\"",
                        first ? "" : ",",
                        name);

                    first = false;

                    if (offset > 1900)
                    {
                        /* Prevent buffer overflow */
                        break;
                    }
                }
            }
        }

        closedir(dir);
    }

    offset = status_append(buf, buf_size, offset, "]}");

    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, buf, offset);

    free(buf);

    return ESP_OK;
}

static esp_err_t upload_post_handler(httpd_req_t *req)
{
    char query[128] = {0};
    char filename[65] = {0};

    if (httpd_req_get_url_query_str(req, query, sizeof(query)) != ESP_OK)
    {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Missing query string");
        return ESP_FAIL;
    }

    if (httpd_query_key_value(query, "filename", filename, sizeof(filename)) != ESP_OK)
    {
        httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Missing filename");
        return ESP_FAIL;
    }

    if (!is_valid_filename(filename))
    {
        httpd_resp_send_err(
            req,
            HTTPD_400_BAD_REQUEST,
            "Invalid filename. Use alphanumeric, dot, dash, underscore. Max 64 chars. Must end in .pcm or .bmp");

        return ESP_FAIL;
    }

    char tmp_path[140];
    char final_path[140];

    snprintf(tmp_path, sizeof(tmp_path), SD_MOUNT_POINT "/%s.tmp", filename);
    snprintf(final_path, sizeof(final_path), SD_MOUNT_POINT "/%s", filename);

    ESP_LOGI(TAG, "Upload start: %s", final_path);

    if (lvgl_port_lock(100))
    {
        ui_set_transfer_status("Uploading...");
        lvgl_port_unlock();
    }

    FILE *f = fopen(tmp_path, "wb");

    if (!f)
    {
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Cannot create file on SD");
        return ESP_FAIL;
    }

    size_t remaining = req->content_len;
    size_t total_written = 0;

    static char rx_buffer[4096]; /* static to save stack */

    bool failed = false;

    while (remaining > 0)
    {
        size_t to_read = remaining < sizeof(rx_buffer) ? remaining : sizeof(rx_buffer);

        int received = httpd_req_recv(req, rx_buffer, to_read);

        if (received <= 0)
        {
            if (received == HTTPD_SOCK_ERR_TIMEOUT)
            {
                /* Retry on timeout */
                continue;
            }

            ESP_LOGE(TAG, "Upload receive failed");
            failed = true;
            break;
        }

        size_t written = fwrite(rx_buffer, 1, received, f);

        if (written != (size_t)received)
        {
            ESP_LOGE(TAG, "SD write failed");
            failed = true;
            break;
        }

        remaining -= received;
        total_written += written;

        /* Update UI progress occasionally */
        if ((total_written % (64 * 1024)) < sizeof(rx_buffer))
        {
            if (lvgl_port_lock(10))
            {
                ui_update_transfer_progress(total_written, req->content_len);
                lvgl_port_unlock();
            }
        }
    }

    fclose(f);

    if (failed)
    {
        remove(tmp_path);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Upload failed");
        return ESP_FAIL;
    }

    remove(final_path); /* Replace if exists */

    if (rename(tmp_path, final_path) != 0)
    {
        remove(tmp_path);
        httpd_resp_send_err(req, HTTPD_500_INTERNAL_SERVER_ERROR, "Rename failed");
        return ESP_FAIL;
    }

    ESP_LOGI(TAG, "Upload complete: %s (%u bytes)", final_path, (unsigned)total_written);

    if (lvgl_port_lock(100))
    {
        ui_set_transfer_status("Upload complete!");
        ui_update_transfer_progress(100, 100);
        lvgl_port_unlock();
    }

    httpd_resp_set_type(req, "application/json");
    httpd_resp_send(req, "{\"ok\":true}", HTTPD_RESP_USE_STRLEN);

    return ESP_OK;
}

/* --------------------------------------------------------------------------
 * Public API
 * -------------------------------------------------------------------------- */
esp_err_t http_upload_server_start(void)
{
    if (s_upload_server != NULL)
    {
        return ESP_OK;
    }

    httpd_config_t config = HTTPD_DEFAULT_CONFIG();

    config.server_port = 80;
    config.stack_size = 8192;
    config.max_uri_handlers = 8;
    config.recv_wait_timeout = 30; /* seconds */
    config.send_wait_timeout = 30; /* seconds */

    esp_err_t ret = httpd_start(&s_upload_server, &config);

    if (ret != ESP_OK)
    {
        ESP_LOGE(TAG, "Failed to start HTTP server: %s", esp_err_to_name(ret));
        return ret;
    }

    httpd_uri_t root_uri = {
        .uri = "/",
        .method = HTTP_GET,
        .handler = root_get_handler,
    };

    httpd_register_uri_handler(s_upload_server, &root_uri);

    httpd_uri_t upload_uri = {
        .uri = "/upload",
        .method = HTTP_POST,
        .handler = upload_post_handler,
    };

    httpd_register_uri_handler(s_upload_server, &upload_uri);

    httpd_uri_t status_uri = {
        .uri = "/status",
        .method = HTTP_GET,
        .handler = status_get_handler,
    };

    httpd_register_uri_handler(s_upload_server, &status_uri);

    ESP_LOGI(TAG, "HTTP upload server started");

    return ESP_OK;
}

esp_err_t http_upload_server_stop(void)
{
    if (s_upload_server != NULL)
    {
        httpd_stop(s_upload_server);
        s_upload_server = NULL;

        ESP_LOGI(TAG, "HTTP upload server stopped");
    }

    return ESP_OK;
}